name: weixin

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # 每天温哥华时间上午8:30运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/America/Vancouver /etc/localtime

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run weixin
        run: |
          python3 main.py
